language: go

install:
  - go get -v github.com/BobWong/golog
  - go get -v github.com/davyxu/goobjfmt

go:
  - 1.10

script:
  - go test -v github.com/BobWong/cellnet/tests

after_success:
  - bash <(curl -s https://codecov.io/bash)