language: go

install:
  - go get -v github.com/bobwong89757/golog
  - go get -v github.com/bobwong89757/goobjfmt

go:
  - 1.10

script:
  - go test -v github.com/bobwong89757/cellnet/tests

after_success:
  - bash <(curl -s https://codecov.io/bash)