// Auto generated by github.com/bobwong89757/cellmesh/protogen
// DO NOT EDIT!

package proto

import (
	"github.com/bobwong89757/cellnet"
	"github.com/bobwong89757/cellnet/codec"
	_ "github.com/bobwong89757/cellnet/codec/gogopb"
	"reflect"
)

// Make compiler import happy
var (
	_ cellnet.Event
	_ codec.CodecRecycler
	_ reflect.Type
)

func GetMessageHandler(svcName string) cellnet.EventCallback {

	switch svcName {
	}

	return nil
}

func init() {

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*EchoAck)(nil)).Elem(),
		ID:    1001,
	})
}
