// Generated by github.com/bobwong89757/protoplus
// DO NOT EDIT!
package proto

import (
	"github.com/bobwong89757/protoplus/proto"
	"unsafe"
)

var (
	_ *proto.Buffer
	_ unsafe.Pointer
)

func init() {

}
