// Generated by github.com/BobWong/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: pb.proto

package test

import (
	"github.com/BobWong/cellnet"
	"reflect"
	_ "github.com/BobWong/cellnet/codec/gogopb"
	"github.com/BobWong/cellnet/codec"
)

func init() {

	// pb.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*ContentACK)(nil)).Elem(),
		ID:    60952,
	})
}
